import "@/styles/global.css.ts";
import type { Metadata } from "next";
import AppProviders from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="{lightThemeClass}">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
